# Generated by Django 4.2.7 on 2025-11-07 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accessibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routefeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessibilityreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accessibilityreport',
            index=models.Index(fields=['latitude', 'longitude'], name='accessibili_latitud_506524_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityreport',
            index=models.Index(fields=['severity', 'status'], name='accessibili_severit_f5853d_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityreport',
            index=models.Index(fields=['created_at'], name='accessibili_created_f0c458_idx'),
        ),
    ]
